#!/bin/bash

replacevhost=$1;
replacedomain=$2;
replacesitesdir=""
ava="/etc/apache2/sites-available";
ena="/etc/apache2/sites-enabled";

if [[ ${replacevhost} == "" || ${replacedomain} == "" ]]; then
    echo "Usage: mkvhost <replacevhost> <replacedomain> <environment>";
    echo "Example: mkvhost www example.com production";
    echo "         will create the virtual host for www.example.com";
    exit 0;
else
    vhost="${replacevhost}.${replacedomain}";
fi

# Set default env if none passed.
if [ -z $3 ]
then
    env="production"
else
    env=$3
fi

# Set site directory based on evnvironment.
case "$env" in
    "production")
        replacesitesdir="/var/www" ;;
    "local")
        replacesitesdir="/var/www/sites" ;;
    *)
        replacesitesdir="/var/www" ;;

esac

# Create http host
if [[ -e ${ava}/${vhost} ]]; then
    echo "${ava}/${vhost} already exists. Skipping.";
elif [[ -e ${ena}/${vhost} ]]; then
    echo "${ena}/${vhost} already exists. Skipping.";
else
    if [[ ! -e ${ava}/template.http ]]; then
        echo "${ava}/template.http does not exist. Cannot create ${ena}/${vhost}.";
    else
        cat ${ava}/template.http | sed "s/replacevhost/${replacevhost}/g" | sed "s/replacedomain/${replacedomain}/g" | sed "s/replacesitesdir/$(printf '%q' $replacesitesdir)/g" > ${ava}/${vhost}
    fi
fi

# Create http ssl host
#if [[ -e ${ava}/${vhost}.ssl ]]; then
#    echo "${ava}/${vhost}.ssl already exists. Skipping.";
#elif [[ -e ${ena}/${vhost}.ssl ]]; then
#    echo "${ena}/${vhost}.ssl already exists. Skipping.";
#else
#    if [[ ! -e ${ava}/template.http.ssl ]]; then
#        echo "${ava}/template.http.ssl does not exist. Cannot create ${ena}/${vhost}.ssl.";
#    else
#        cat ${ava}/template.http.ssl | sed "s/replacevhost/${replacevhost}/g" | sed "s/replacedomain/${replacedomain}/g" > ${ava}/${vhost}.ssl
#    fi
#fi

bool="n";
echo -n "Should I enable ${ava}/${vhost}? ";
read bool;
if [[ ${bool} == "y" || ${bool} == "Y" || ${bool} == "yes" || ${bool} == "YES" || ${bool} == "Yes" ]]; then
    if [[ -e ${ena}/${vhost} ]]; then
        echo "Host was already enabled.";
    else
        if [[ ! -e ${ava}/${vhost} ]]; then
            echo "${ava}/${vhost} does not exist so I cannot enable it.";
        else
            echo "Running: a2ensite ${vhost}";
            a2ensite ${vhost};
        fi
    fi
fi

#bool="n";
#echo -n "Should I enable ${ava}/${vhost}.ssl? ";
#read bool;
#if [[ ${bool} == "y" || ${bool} == "Y" || ${bool} == "yes" || ${bool} == "YES" || ${bool} == "Yes" ]]; then
#    if [[ -e ${ena}/${vhost}.ssl ]]; then
#        echo "Host was already enabled.";
#    else
#        if [[ ! -e ${ava}/${vhost}.ssl ]]; then
#            echo "${ava}/${vhost}.ssl does not exist so I cannot enable it.";
#        else
#            echo "Running: cp ${ava}/${vhost}.ssl ${ena}/${vhost}.ssl";
#            cp ${ava}/${vhost}.ssl ${ena}/${vhost}.ssl;
#        fi
#    fi
#fi

bool="n";
echo -n "Should I create ${replacesitesdir}/${vhost} for you? ";
read bool;
if [[ ${bool} == "y" || ${bool} == "Y" || ${bool} == "yes" || ${bool} == "YES" || ${bool} == "Yes" ]]; then
    if [[ -e ${replacesitesdir}/${vhost} ]]; then
        echo "${replacesitesdir}/${vhost} already existed.";
    else
        mkdir -p ${replacesitesdir}/${vhost}/current/public;
        chown -R www-data:www-data ${replacesitesdir}/${vhost}/current;
        chmod -R 775 ${replacesitesdir}/${vhost};
        mkdir -p /var/log/apache2/${vhost};
    fi
fi

bool="n";
echo -n "Should I reload Apache? ";
read bool;
if [[ ${bool} == "y" || ${bool} == "Y" || ${bool} == "yes" || ${bool} == "YES" || ${bool} == "Yes" ]]; then
    echo "Running: service apache2 restart";
    service apache2 reload;
fi
