<VirtualHost *:80>
        ServerAdmin gareth.foote+replacevhost.replacedomain@gmail.com

        ServerName replacevhost.replacedomain
        DocumentRoot replacesitesdir/replacevhost.replacedomain/current/public
        <Directory />
                Options FollowSymLinks
                AllowOverride None
        </Directory>
        <Directory replacesitesdir/replacevhost.replacedomain/current/public>
                Options All MultiViews ExecCGI
                AllowOverride all
                Order allow,deny
                allow from all
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/replacevhost.replacedomain/error.log
        # Possible values include: debug, info, notice, warn, error, crit,
        # alert, emerg.
        # LogLevel warn
        CustomLog ${APACHE_LOG_DIR}/replacevhost.replacedomain/access.log combined
</VirtualHost>
